valory-xyz/autonolas-tokenomics

scripts/deployment/deploy_10_14_change_ownerships.js

- Fixing a bug in the script. The new owner must be Timelock.

fix: donatorBlacklist deployment patch

---

.gitleaksignore
audits/internal3/README.md

- Re-audit ref to change 104 to 106 pull

doc: update audit3 ref: pull104 to pull106

---

package.json
scripts/fork/add_remove_liquidity_calculate_LP_hardhat.js
scripts/fork/ganache_node_with_timelock_account.js
scripts/proposals/proposal_03_calculate_LP.js
scripts/proposals/proposal_04_change_depository_and_manage_products.js
test/Depository.js
yarn.lock

- Updating scripts for proposals, fork-related routines.

chore: updating priceLP scripts

---

scripts/proposals/proposal_05_create_bonding_products.js

- Adding a proposal to create new bonding products.

chore: adding a proposal to create new bonding products

---

CHANGELOG.md
audits/README.md

doc: adding changelog

---

scripts/proposals/proposal_03_calculate_LP.js
scripts/proposals/proposal_05_create_bonding_products.js
scripts/proposals/proposal_06_change_fractions_and_manage_products.js

- Correcting bonding proposals;
- Updating a script for LP price calculation.

chore: correcting proposals

---

scripts/fork/ganache_enable_LP_token_create_bonding_product.js
scripts/fork/ganache_node_calculate_price_LP_APY.js

- Adding a script to enable a new token in Treasury and create bonding products.

chore: adding a script to enable a new token in Treasury

---

scripts/analyzers/code_line_report.txt

final_SoCl

---

contracts/Dispenser.sol
contracts/staking/ArbitrumDepositProcessorL1.sol
contracts/staking/DefaultTargetDispenserL2.sol
contracts/staking/EthereumDepositProcessor.sol
contracts/staking/GnosisDepositProcessorL1.sol
contracts/staking/OptimismDepositProcessorL1.sol
contracts/staking/PolygonDepositProcessorL1.sol
contracts/staking/WormholeDepositProcessorL1.sol
contracts/staking/WormholeTargetDispenserL2.sol
test/StakingBridging.js

- Addressing C4R [issue 26](https://github.com/code-423n4/2024-05-olas-findings/issues/26).

refactor and test: addressing C4R issue 26

---

.gitleaksignore
docs/configuration.json

- Update tokenomics implementation address version 1.2.0.

chore: update tokenomics implementation address

---

audits/README.md
audits/internal5/README.md
contracts/Dispenser.sol

V1.2.2 internal audit

---

audits/internal5/README.md

- Updated the internal audit README file based on changes over the past week.

doc: catch up on changes

---

contracts/Dispenser.sol

- Adding staking claiming events info.

chore: adding staking claiming events info

---

.gitleaksignore
docs/configuration.json
scripts/deployment/staking/mode/deploy_11_mode_target_dispenser.js

chore: deployment on mode

---

audits/internal6/README.md

doc: check-erc-721 in audit

---

scripts/proposals/proposal_14_fund_contracts_from_leftovers_gnosis2.js
scripts/proposals/proposal_15_close_all_bonding_products.js

chore: adding proposal scripts

---

audits/internal6/README.md
contracts/Tokenomics.sol
contracts/TokenomicsConstants.sol
hardhat.config.js
scripts/fork/tokenomics_retain_calculation.js
scripts/fork/tokenomics_update_with_timelock_account.js
test/Tokenomics.js

- Another round of inflation update.

refactor: another round of inflation update

---

contracts/TokenomicsConstants.sol
hardhat.config.js
package.json
test/Depository.t.sol
test/Dispenser.t.sol
test/Treasury.t.sol
yarn.lock

- Contract bytecode length optimization.

refactor: contract bytecode lenght optimization

---

audits/README.md
audits/internal7/README.md
yarn.lock

- Internal audit based on DefaultTargetDispenserL2 update

doc: internal audit 7

---

audits/README.md
audits/internal7/README.md
test/StakingBridging.js
yarn.lock

test: adding test

---

scripts/proposals/proposal_17_change_incentive_fractions.js

- Adding script to change incentives fractions.

chore: adding script to change incentives fractions

---

scripts/deployment/staking/base/globals_base_mainnet.json

chore: correcting base chain id
